#!usr/bin/bash
mkdir ./git_repo/
git clone https://github.com/McSCert/Simulink-Utility.git
git clone https://github.com/McSCert/Model-Comparison-Utility.git
git clone https://github.com/McSCert/Flatten-Subsystem.git
git clone https://github.com/McSCert/Data-Store-Rescope.git
git clone https://github.com/McSCert/LineToGotoFrom.git
git clone https://github.com/McSCert/Signature.git
git clone https://github.com/McSCert/C2Flowchart.git
git clone https://github.com/McSCert/Simulink-Design-Documenter.git
git clone https://github.com/McSCert/Simulink-Logic-Simplifier.git
git clone https://github.com/McSCert/Auto-Layout.git
git clone https://github.com/McSCert/Obfuscate-Model.git
git clone https://github.com/McSCert/Simulink-Module.git
git clone https://github.com/McSCert/Reach-Coreach.git
git clone https://github.com/McSCert/Intersection-Navigation-and-Path-Estimation.git
git clone https://github.com/CATIA-Systems/FMIKit-Simulink.git
git clone https://github.com/python/cpython.git
git clone https://github.com/niello/deusexmachina.git
git clone https://github.com/microsoft/vcpkg.git
git clone https://github.com/tj/git-extras.git
git clone https://github.com/ghorwin/MasterSim.git
git clone https://github.com/dapperfu/Python-Simulink.git
git clone https://github.com/opencv/opencv.git
git clone https://github.com/modelica/ModelicaStandardLibrary.git
git clone https://github.com/CATIA-Systems/FMPy.git
git clone https://github.com/mathworks/matlab-with-python.git
git clone https://github.com/Kitware/CMake.git
git clone https://github.com/mathworks/jenkins-matlab-plugin.git
git clone https://github.com/mathworks/MathWorks-Excellence-in-Innovation.git
git clone https://github.com/hadrianhu888/FMI_test_7.git
git clone https://github.com/hadrianhu888/FMI_test_6.git
git clone https://github.com/hadrianhu888/FMI_test_5.git
git clone https://github.com/hadrianhu888/FMI_test_4.git
git clone https://github.com/hadrianhu888/FMI_test_3.git
git clone https://github.com/hadrianhu888/FMI_test_2.git
git clone https://github.com/hadrianhu888/FMI_test_1.git
git clone https://github.com/hadrianhu888/stateflow_FMU_test.git
git clone https://github.com/hadrianhu888/batch_cmds.git 
git clone https://github.com/hadrianhu888/matlab_bats.git
git clone https://github.com/hadrianhu888/python_challenges.git
git clone https://github.com/hadrianhu888/fmi_test_example.git
git clone https://github.com/hadrianhu888/DHH_VoltReg.git
git clone https://github.com/hadrianhu888/pytest_unittest_projects.git
git clone https://github.com/hadrianhu888/cpp_challenges.git
git clone https://github.com/hadrianhu888/Project_1.git
git clone https://github.com/hadrianhu888/batch_files.git
git clone https://github.com/hadrianhu888/batch_file_copy_paste.git
git clone https://github.com/hadrianhu888/absolute_cpp.git
git clone https://github.com/hadrianhu888/perl_practice.git
git clone https://github.com/hadrianhu888/VSProject.git
git clone https://github.com/hadrianhu888/QB64.git
git clone https://github.com/hadrianhu888/qb64_2022.git
git clone https://github.com/hadrianhu888/labs_shared.git
git clone https://github.com/hadrianhu888/batteryParameterEstimation.git
git clone https://github.com/openqasm/openqasm.git
exit
