#! /bin/bash
git clone https://github.com/0ad/0ad.git
git clone https://github.com/hadrianhu888/absolute_cpp_new.git
git clone https://github.com/hadrianhu888/batch_cmds.git
git clone https://github.com/Corp13278247/BatteryManagementSystemInspiration.git
git clone https://github.com/hadrianhu888/batteryParameterEstimation.git
git clone https://github.com/tgraupmann/ChromaDiscordApp.git
git clone https://github.com/quantumlib/Cirq.git
git clone https://github.com/dotnet/csharp-notebooks
git clone https://github.com/hadrianhu888/C_DS_Algo.git
git clone https://github.com/hadrianhu888/C_For_Dummies.git
git clone https://github.com/hadrianhu888/DiscordJiraApp.git
git clone https://github.com/Entanglion/entanglion.git
git clone https://github.com/hadrianhu888/FMIKit-Simulink.git
git clone https://github.com/git/git
git clone https://github.com/sensorflo/git-draw.git
git clone https://github.com/github/gitignore.git
git clone https://github.com/google/googletest.git
git clone https://github.com/hadrianhu888/java_tests_new.git
git clone https://github.com/jesseduffield/lazygit.git
git clone https://github.com/hadrianhu888/leetcode_challenges.git
git clone https://github.com/robinrowe/libunistd.git
git clone https://github.com/hadrianhu888/linear_algebra_lan_2023.git
git clone https://github.com/mathworks/Lunar-Mission-Trajectory-Inspired-by-Artemis-I-Mission.git
git clone https://github.com/marktext/marktext.git
git clone https://github.com/hadrianhu888/matlab_tutorial_questions.git
git clone https://github.com/nandland/nandland.git
git clone https://github.com/openqasm/openqasm.git
git clone https://github.com/openqasm/oqpy.git
git clone https://github.com/PennyLaneAI/pennylane.git
git clone https://github.com/hadrianhu888/perl_practice_2.git
git clone https://github.com/heroku/python-getting-started.git
git clone https://github.com/PacktPublishing/Python-Object-Oriented-Programming---4th-edition.git
git clone https://github.com/hadrianhu888/Python-Simulink.git
git clone https://github.com/hadrianhu888/python_crash_course.git
git clone https://github.com/hadrianhu888/Quantum_Compute_2022.git
git clone https://github.com/quil-lang/quil.git
git clone https://github.com/mathworks/Simscape-HEV-Series-Parallel.git
git clone https://github.com/microsoft/vcpkg.git
git clone https://github.com/hadrianhu888/absolute_cpp_new.git
git clone https://github.com/hadrianhu888/batch_cmds.git
git clone https://github.com/Corp13278247/BatteryManagementSystemInspiration.git
git clone https://github.com/hadrianhu888/batteryParameterEstimation.git
git clone https://github.com/tgraupmann/ChromaDiscordApp.git
git clone https://github.com/quantumlib/Cirq.git
git clone https://github.com/dotnet/csharp-notebooks
git clone https://github.com/hadrianhu888/C_DS_Algo.git
git clone https://github.com/hadrianhu888/C_For_Dummies.git
git clone https://github.com/hadrianhu888/DiscordJiraApp.git
git clone https://github.com/Entanglion/entanglion.git
git clone https://github.com/hadrianhu888/FMIKit-Simulink.git
git clone https://github.com/git/git
git clone https://github.com/sensorflo/git-draw.git
git clone https://github.com/github/gitignore.git
git clone https://github.com/google/googletest.git
git clone https://github.com/hadrianhu888/java_tests_new.git
git clone https://github.com/jesseduffield/lazygit.git
git clone https://github.com/hadrianhu888/leetcode_challenges.git
git clone https://github.com/robinrowe/libunistd.git
git clone https://github.com/hadrianhu888/linear_algebra_lan_2023.git
git clone https://github.com/mathworks/Lunar-Mission-Trajectory-Inspired-by-Artemis-I-Mission.git
git clone https://github.com/marktext/marktext.git
git clone https://github.com/hadrianhu888/matlab_tutorial_questions.git
git clone https://github.com/nandland/nandland.git
git clone https://github.com/openqasm/openqasm.git
git clone https://github.com/openqasm/oqpy.git
git clone https://github.com/PennyLaneAI/pennylane.git
git clone https://github.com/hadrianhu888/perl_practice_2.git
git clone https://github.com/heroku/python-getting-started.git
git clone https://github.com/PacktPublishing/Python-Object-Oriented-Programming---4th-edition.git
git clone https://github.com/hadrianhu888/Python-Simulink.git
git clone https://github.com/hadrianhu888/python_crash_course.git
git clone https://github.com/hadrianhu888/Quantum_Compute_2022.git
git clone https://github.com/quil-lang/quil.git
git clone https://github.com/mathworks/Simscape-HEV-Series-Parallel.git
git clone https://github.com/microsoft/vcpkg.git
